project:
  type: website
  output-dir: _site

website:
  title: "Proxecto AGROSOLVENTS"
  description: "Informe final de investigación - Universidade de Vigo"
  navbar:
    background: primary
    left:
      - href: memoria_final.qmd
        text: Resumo Executivo
      - text: "Seccións"
        menu:
          - href: Informe_Final_Investigacion_Agrosolvents.md
            text: "Introdución"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    number-sections: true
  pdf:
    documentclass: report
    papersize: a4
    number-sections: true
    toc: true
    colorlinks: true

editor: visual


